mailConfig:
  #protocol: smtp
  host: smtp.gmail.com
  port: 465
  auth: true
  user: noreply.test.vn.01
  password: noreply@2012

mailNotification:
  general:
    subject: No-reply - NOTIFICATION from Activity
    sender: noreply.test.vn.01@gmail.com
    recipients:
      - ducquoc@kms-technology.com
      #- ducquoc.vn@gmail.com
